name: CI with Maven

on:
  push:
    branches: [ SDET-2 ]
  pull_request:
    branches: [ SDET-2 ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Build Java examples with Maven
        run: mvn clean test

      - uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
