name: CI with Maven

on:
  push:
    branches: [ SDET-2 ]
  pull_request:
    branches: [ SDET-2 ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout проекта с тестами
        uses: actions/checkout@v4

      - name: Клонирование API-сервиса
        run: git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git api-service

      - name: Создание .env файла
        run: |
          cat <<EOF > api-service/.env
          POSTGRES_USER=test
          POSTGRES_PASSWORD=test
          POSTGRES_DB=test
          POSTGRES_HOST=postgres
          POSTGRES_PORT=5432
          HTTP_PORT=8080
          LOGGER_FORMAT=json
          EOF

      - name: Запуск API-сервиса через Docker Compose
        run: |
          cd api-service
          docker compose up -d

      - name: Ожидание запуска API-сервиса
        run: |
          echo "Ожидаем http://localhost:8080/api/_/docs/swagger/index.html..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/api/_/docs/swagger/index.html | grep -q "Swagger"; then
              echo "Сервис поднят!"
              exit 0
            fi
            echo "Ожидание..."
            sleep 3
          done
          echo "Сервис не поднялся вовремя" >&2
          docker compose logs service || true
          exit 1

      - name: Установка Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Запуск тестов
        run: mvn clean test